"""add source_url to songs

Revision ID: 315baecc3cc6
Revises: ecdedf64cd99
Create Date: 2026-05-27 16:11:13.387165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '315baecc3cc6'
down_revision: Union[str, None] = 'ecdedf64cd99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'songs', ['source_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_column('songs', 'source_url')
    # ### end Alembic commands ###
