"""add_account_lockout_fields

Revision ID: 4b65c594df5d
Revises: ee4a1f9083ff
Create Date: 2026-06-01 10:07:32.330746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b65c594df5d'
down_revision: Union[str, None] = 'ee4a1f9083ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_providers', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('auth_providers', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_providers', 'locked_until')
    op.drop_column('auth_providers', 'failed_login_count')
    # ### end Alembic commands ###
