"""add_session_device_fields

Revision ID: ee4a1f9083ff
Revises: 50cdcd04cdb1
Create Date: 2026-06-01 09:49:44.200951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee4a1f9083ff'
down_revision: Union[str, None] = '50cdcd04cdb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_name', sa.String(length=200), nullable=True))
    op.add_column('refresh_tokens', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'platform')
    op.drop_column('refresh_tokens', 'device_name')
    # ### end Alembic commands ###
